version: '3.8'  # docker-compose 파일 버전

services:
  learningFlow: # 서비스 이름
    image: mysql:8.0  # 사용할 Docker 이미지 (MySQL 8.0)
    container_name: learningFlow_db  # 컨테이너 이름
    restart: always  # 컨테이너 재시작 정책
    environment:
      MYSQL_ROOT_PASSWORD: root1234  # 루트 사용자 비밀번호
      MYSQL_DATABASE: learningFlow_db  # 기본 생성 DB 이름
      MYSQL_USER: learningFlow  # 사용자 이름
      MYSQL_PASSWORD: learningFlow123  # 사용자 비밀번호
    ports:
      - "3307:3306"  # 호스트와 컨테이너 간 포트 매핑
    volumes:
      - db_data:/var/lib/mysql  # 데이터 지속성을 위한 볼륨 매핑

volumes:
  db_data:
