spring:
  datasource:
#        url: jdbc:mysql://localhost:3307/learningFlow_db  # MySQL
#        username: learningFlow                           # MySQL
#        password: learningFlow123                        # MySQL
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#        driver-class-name: com.mysql.cj.jdbc.Driver      # MySQL JDBC
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update                               
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true                                   # SQL ?? ??
  sql:
    init:
      mode: always                                   # SQL ??? ??
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://onboarding.p-e.kr/login/oauth2/code/google"
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          ssl.trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
          auth.mechanisms: XOAUTH2  # 추가: OAuth2 인증 메커니즘 지정
          sasl:
            enable: true            # 추가: SASL 인증 활성화
            mechanisms: XOAUTH2     # 추가: SASL 메커니즘으로 XOAUTH2 사용
          auth.xoauth2.disable: false  # 추가: XOAUTH2 비활성화 옵션 끄기
        transport:
          protocol: smtp

gmail:
  client:
    id: ${GMAIL_CLIENT_ID}
    secret: ${GMAIL_CLIENT_SECRET}
  refresh:
    token: ${GMAIL_REFRESH_TOKEN}

# JWT 설정 추가
custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    access-token-validity-in-seconds: 3600    # Access Token 1시간
    refresh-token-validity-in-seconds: 604800 # Refresh Token 1주일

app:
  frontend-url: https://onboarding-kappa.vercel.app/ #http://54.180.118.227:8080

server:
  port: 8080
  compression:
    enabled: true  # Gzip 압축
    mime-types: application/json
    min-response-size: 20480

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

cloud:
  aws:
    s3:
      bucket: learningflow
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

#     org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
