spring:
  datasource:
    url: jdbc:mysql://localhost:3307/learningFlow_db  # Docker?? ?? ?? MySQL ??
    username: learningFlow                           # Docker Compose?? ??? ??? ??
    password: learningFlow123                        # Docker Compose?? ??? ????
    driver-class-name: com.mysql.cj.jdbc.Driver      # MySQL JDBC ????
  jpa:
    hibernate:
      ddl-auto: update                               # ??? ?? ???? (?? ????? ??)
    show-sql: true                                   # SQL ?? ??
  sql:
    init:
      mode: always                                   # SQL ??? ??

server:
  port: 8080                                         # Spring Boot ?????? ?? ??
