spring:
  datasource:
    url: jdbc:mysql://localhost:3307/learningFlow_db  # Docker?? ?? ?? MySQL ??
    username: learningFlow                           # Docker Compose?? ??? ??? ??
    password: learningFlow123                        # Docker Compose?? ??? ????
    driver-class-name: com.mysql.cj.jdbc.Driver      # MySQL JDBC ????
  jpa:
    hibernate:
      ddl-auto: update                               # ??? ?? ???? (?? ????? ??)
    show-sql: true                                   # SQL ?? ??
  sql:
    init:
      mode: always                                   # SQL ??? ??
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET}
            scope:
              - email
              - profile


server:
  port: 8080                                         # Spring Boot ?????? ?? ??
