spring:
  datasource:
    url: jdbc:mysql://localhost:3307/learningFlow_db  # Docker?? ?? ?? MySQL ??
    username: learningFlow                           # Docker Compose?? ??? ??? ??
    password: learningFlow123                        # Docker Compose?? ??? ????
    driver-class-name: com.mysql.cj.jdbc.Driver      # MySQL JDBC ????
  jpa:
    hibernate:
      ddl-auto: create               # ??? ?? ???? (?? ????? ??)
    show-sql: true                                   # SQL ?? ??
  sql:
    init:
      mode: always                                   # SQL ??? ??
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET}
            scope:
              - email
              - profile
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

# JWT 설정 추가
custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    access-token-validity-in-seconds: 3600    # Access Token 1시간
    refresh-token-validity-in-seconds: 604800 # Refresh Token 1주일

app:
  url: http://localhost:8080

server:
  port: 8080                                         # Spring Boot ?????? ?? ??

