INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 7, 19, 12, 'Overview');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 7, 20, 13, 'Classification (1) Introduction');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 7, 21, 14, 'Cross-validation (1) Overview');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 7, 22, 15, 'Cross-validation (2) Validation set approach');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 7, 23, 16, 'Cross-validation (3) Leave-one-out cross-validation (LOOCV)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 7, 24, 17, 'Cross-validation (4) k-fold cross-validation');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 7, 25, 18, 'Classification (2) Decision Tree');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 7, 26, 19, 'Classification (3) Ensemble methods - Bagging');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (9, 7, 27, 20, 'Classification (4) Ensemble methods - Random forest');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (10, 7, 28, 21, 'Classification (5) Ensemble methods - Boosting(AdaBoost)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (11, 7, 29, 22, 'Classification (6) Confusion Matrix');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 8, 30, 23, 'Design Project #1 서비스디자인 미니 프로젝트 1주차 이야기, 주제를 정하다!');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 8, 31, 24, 'Design Project #2 여섯 명의 인터뷰이를 만나다& 쉽지 않은 어피니티 다이어그램');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 8, 32, 25, 'Design Project #3 어피니티 다이어그램 이용해서 퍼소나 만들기 1탄');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 8, 33, 26, 'Design Project #4 퍼소나 만들기 2탄');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 8, 34, 27, 'Design Project #5 퍼소나를 기반으로 유저시나리오 User Scenario 만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 8, 35, 28, 'Design Project #6 라-프레쉬(가제) User Flow 그리기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 8, 36, 29, 'Design Project #7 미준맵 그리기 ');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 10, 42, 35, 'React.memo로 컴포넌트 최적화하기 (ft. useMemo, useCallback)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 10, 43, 36, 'React.Fragment는 무엇? 리액트 개발자라면 꼭 알아야됨');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 10, 44, 37, 'React의 가상돔 (Virtual DOM)이 뭔가요?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 10, 45, 38, 'eact - List와 Key의 중요성. 디버깅의 악몽을 피하자!');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 10, 46, 39, 'React의 ForwardRef란? | Ref 전달하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 10, 47, 40, '리액트 디바운스 - Debounce로 서버 비용 아끼는법 | React Custom Hook');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 10, 48, 41, '리액트 쓰로틀링 - 함수도 쿨타임이 필요하다 | Throttle | React Custom Hook');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 11, 49, 42, 'Figma 프로젝트 관리 및 파일 공유');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 11, 50, 43, 'Figma로 개발자와 협업하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 11, 51, 44, 'Figma의 팀 라이브러리 기능');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 12, 52, 45, '연정\'s figma New 피그마 온보딩 2022');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 12, 53, 46, 'Figma에 의한 디자인 시스템 구축 사례 및 개념 정의');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 12, 54, 47, '실무를 위한 Figma 시작 가이드 (feat. 피그마에 최적화된 디자인 시스템 구축)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 12, 55, 48, 'New 오토 레이아웃 기본 익히기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 12, 56, 49, '디자인 시스템을 위한 핵심 기능 Variants');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 12, 57, 50, '재사용 가능한 버튼 컴포넌트 생성하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 12, 58, 51, '다크모드를 위한 컬러 Variables 기능');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 12, 59, 52, '반응형 레이아웃을 위한 Auto Layout 기능');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (9, 12, 60, 53, '디자인 시스템 관련 레퍼런스');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 13, 61, 30, 'Var Let Const 차이 완벽정리 (스코프, 호이스팅)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 13, 62, 31, 'This와 Bind | 멋진 개발자라면 꼭 알아야됨!!');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 13, 63, 32, '화살표 함수 #1 (기본편) | 일반 함수 VS 화살표 함수');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 13, 64, 33, '화살표 함수 #2 (this 편) | 일반 함수와 화살표 함수의 THIS');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 13, 65, 34, 'Callback functions 콜백함수란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 14, 66, 54, 'Type of statistics (Descriptive / Inferential)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 14, 67, 55, 'Central tendency (중심경향성)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 14, 68, 56, 'Variability (산포도)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 14, 69, 57, 'Sample variance(표본분산)과 degree of freedom(자유도) n-1');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 14, 70, 58, 'Types of measurement scale');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 14, 71, 59, 'Data type');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 14, 72, 60, 'Random variable (확률변수) - (1) Definition');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 14, 73, 61, 'Random variable (확률변수) - (2) 누적분포함수, 이산확률변수, 연속확률변수');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (9, 14, 74, 62, 'Probability mass function (확률질량함수) / Probability density function (확률밀도함수)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (10, 14, 75, 63, 'Normal distribution(정규분포)/Central limit theorem(중심극한정리)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (11, 14, 76, 64, 'Z-score');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (12, 14, 77, 65, 'Hypothesis testing (가설검정)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (13, 14, 78, 66, 'P-value / Critical value');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (14, 14, 79, 67, 'Z-test (Z검정)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (15, 14, 80, 68, 'Type I Error / Type II error (1종 오류 / 2종 오류 / 검정력)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (16, 14, 81, 69, 't-test (t검정) - (1) Introduction');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (17, 14, 82, 70, 't-test (t검정) - (1) SPSS output');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (18, 14, 83, 71, 't-test (t검정) - (3) R output');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (19, 14, 84, 72, 'Effect size (효과크기) / cohen’s d');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (20, 14, 85, 73, 'Confidence level (신뢰수준) / Confidence interval (신뢰구간)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 15, 86, 74, 't-test (t검정) - (1) Introduction');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 15, 87, 75, 't-test (t검정) - (1) SPSS output');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 15, 88, 76, 't-test (t검정) - (1) R output');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 16, 89, 77, 'ANOVA (분산분석) (1) - Introduction');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 16, 90, 78, 'ANOVA (분산분석) (2) - One-way ANOVA and SPSS');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 16, 91, 79, 'ANOVA (분산분석) (3) - One-way ANOVA and R');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 16, 92, 80, 'ANOVA (분산분석) (4) - Factorial ANOVA and SPSS');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 16, 93, 81, 'ANOVA (분산분석) (5) - Factorial ANOVA and R');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 17, 95, 83, 'QA 할 때 고려할 것들');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 17, 96, 84, '[insight] 기획자를 위한 QA에 대한 모든 것 ');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 18, 97, 85, 'JOIN(조인) 정리(INNER / LEFT / RIGHT / OUTER / CROSS / SELF)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 18, 98, 86, 'SQL Injection이란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 18, 99, 87, 'SQL과 NoSQL의 차이 ( 둘 중 어떤 DB을 사용해야 할까? )');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 18, 100, 88, '이상 현상(Anomaly)이란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 18, 101, 89, '인덱스(Index)란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 18, 102, 90, '정규화(Normalization)란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 18, 103, 91, '트랜잭션(Transaction)이란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 18, 104, 92, '트랜잭션 격리 수준(Transaction Isolation Level)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (9, 18, 105, 93, 'Redis란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 19, 106, 94, '엑셀에서 자동화된 회계 보고서 작성하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 19, 107, 95, '간편하고 유용한 엑셀 회계장부 활용법  ');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 19, 108, 96, '엑셀에서 회계를 마스터하기: 재무 보고서를 쉽게 자동화');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 19, 109, 97, '챗지피티 엑셀 업무 자동화 수업으로 업무능률 향상시키기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 19, 110, 98, '엑셀 고수 \'회계사\'의 퇴근시간 당겨주는 엑셀 치트키 기본편! ');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 20, 111, 99, '파이썬 프로젝트. 음성인식기 만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 20, 112, 100, '파이썬 게임 간단한 2D 슈팅 프로젝트');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 20, 113, 101, 'OX퀴즈 파이썬 프로그램 프로젝트');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 20, 114, 102, '파이썬으로 학점계산기 만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 20, 115, 103, '파이썬 BMI 계산기 만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 20, 116, 104, '섭씨 화씨 온도변환기만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 20, 117, 105, '장애물 피하기 게임 만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 21, 119, 110, '[IT창업편] 01. 아이디어를 구체화 하는 방법 (스토리텔링의 중요성)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 21, 120, 111, '[IT창업편] 02. 핵심 솔루션을 도출하는 방법 (서비스기획)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 21, 121, 112, '[IT창업편] 02-2. 내 서비스의 예상고객은 누구일까? (페르소나, 서비스디자인, 저니맵)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 21, 122, 113, '[IT창업편] 03. 웹&앱 설계 기획서 작성하기 (IT창업의 마지막 단계)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 21, 123, 114, 'MVP의 정의와 유형, 개발 접근 방법');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 21, 124, 115, '노코드와 로우코드 개발');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 21, 125, 116, '지속가능 비즈니스 모델을 위한 ‘린 스타트업’');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 21, 126, 117, 'STP전략, SWOT분석, 차별화 전략');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 22, 159, 120, '[타미 김정호] 8품사 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 22, 160, 121, '[타미 김정호] 단어, 구, 절, 문장, 문단이란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 22, 161, 122, '[타미 김정호] 문장의 형식 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 22, 162, 123, '[타미 김정호] 영어의 전치수식어와 후치수식어');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 22, 163, 124, '[타미 김정호] 전치사 to와 to부정사의 to 구별하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 22, 164, 125, '[타미 김정호] 자동사와 타동사란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 22, 165, 126, '[타미 김정호] 영어의 짝개념이란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 22, 166, 127, '[타미 김정호] 이어동사 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (9, 22, 167, 128, '[타미 김정호] 유도부사 there');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (10, 22, 168, 129, '[타미 김정호] 수동태 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (11, 22, 169, 130, '[타미 김정호] 분사, 분사구문 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (12, 22, 170, 131, '[타미 김정호] 동명사 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (13, 22, 171, 132, '[타미 김정호] 가정법 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (14, 22, 172, 133, '[타미 김정호] 현재완료 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (15, 22, 173, 134, '[타미 김정호] to부정사 총정리');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (16, 22, 174, 135, '[타미 김정호] 도치, 강조, 생략 기본개념');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 23, 175, 136, '엑셀 최대값(max),최소값(min) if 함수로 조건 일치값 구하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 23, 176, 137, '엑셀 평균구하기(average), 조건 평균구하기(averageif)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 23, 177, 138, '엑셀 순위구하기(rank함수), 중복값(중복순위, sum함수 조합) 없애기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 23, 178, 139, '엑셀 중복값 성적순위 구하기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 23, 179, 140, '엑셀 순위구하기(Sumproduct, Countif) 상위(%)순위 셀서식 적용');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 23, 180, 141, '엑셀 조건 합계 구하기 sumif함수, countif함수');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 23, 181, 142, '엑셀 중복값 제거 위한 중복값 찾기(COUNTIF 사용예제)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 23, 182, 143, '엑셀 특정문자 개수 세기(countif), 특정문자 포함(find)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 24, 183, 144, '파이썬 코딩 무료 강의 (기본편) - 6시간 뒤면 여러분도 개발자가 될 수 있어요 [나도코딩]');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 24, 184, 145, '파이썬 코딩 무료 강의 (활용편1) - 추억의 오락실 게임을 만들어 보아요. 3시간이면 충분합니다. [나도코딩]');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 24, 185, 146, '파이썬 코딩 무료 강의 (활용편2) - GUI 프로그래밍을 배우고 \'여러 이미지 합치기\' 프로그램을 함께 만들어요. [나도코딩]');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 24, 186, 147, '파이썬 코딩 무료 강의 (활용편3) - 웹 크롤링? 웹 스크래핑! 제가 가진 모든 비법을 알려드리겠습니다. [나도코딩]');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 24, 187, 148, '파이썬 코딩 무료 강의 (활용편4) - 업무자동화(RPA), 이제는 일하는 척(?)만 하세요');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 24, 188, 149, '파이썬 코딩 무료 강의 (활용편5) - 데이터 분석 및 시각화, 이 영상 하나로 끝내세요');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (7, 24, 189, 150, '파이썬 코딩 무료 강의 (활용편6) - OpenCV 이미지 처리, 얼굴 인식을 통한 캐릭터 씌우기를 해보아요');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (8, 24, 190, 151, '파이썬 코딩 무료 강의 (활용편7) - 머신러닝, 영화 추천 시스템 만들기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 25, 191, 152, '[Python] YOLOv5를 활용한 객체 인식(Object Detection) (1)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 25, 192, 153, '[Python] YOLOv5를 활용한 객체 인식(Object Detection) (2)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 25, 193, 154, '[Python] YOLO 모델 학습을 위한 오픈 데이터 셋 준비 (1)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 25, 194, 155, '[Python] YOLO 모델 학습을 위한 오픈 데이터 셋 준비 (2)');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 25, 195, 156, '[Python] 구글 Colab을 활용한 YOLO 모델 학습');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 26, 196, 157, '#1 코틀린(Kotlin) 이란');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 26, 197, 158, '#2. 코틀린 기초문법');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 26, 198, 159, '#3 Nullable Type과 함수, 함수형 프로그래밍');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 27, 199, 160, '오픽 독학 벼락치기 만능답변연습🍁오픽점수 IH, AL일주일 공부');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 27, 200, 161, '토익스피킹 만능답변 🏆토스 레벨6, 7목표 벼락치기 공부용');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 27, 201, 162, '오픽 돌발문제 연습🥇재활용, 명절, 은행, 기술, 교통 등');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 27, 202, 163, '토익스피킹 독학 벼락치기용 만능답변연습😸토스 레벨 6, 7목표');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 27, 203, 164, '토익 스피킹 200만점 레벨 8 답변; 토스 모의고사 전 파트 풀기');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 27, 204, 165, '오픽 al 후기, 서베이 선택 요령, 오픽 공부법; IH 혹은 AL이 목표라면 꼭 보세요');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (1, 28, 205, 166, '취업의 모든것-(1)취업의 본질');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (2, 28, 206, 167, '취업의 모든것-(2)취업 준비, 스펙 쌓기란?');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (3, 28, 207, 168, '취업의 모든것-(3)대외활동, 인턴, 공모전 정보 사이트 추천');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (4, 28, 208, 169, '취업의 모든것-(4)취업 준비[산업 조사, 기업 조사,직무 조사]');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (5, 28, 209, 170, '취업의 모든것-(5)기업 분석 방법, 기업 분석 사이트 추천');
INSERT INTO learningflowdb.collection_episode (episode_number, collection_id, id, resource_id, episode_name) VALUES (6, 28, 210, 171, '취업의 모든것-(6)자기소개서를 위한 경험 정리');
