INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (7, '머신러닝');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (7, '의사결정나무');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (7, '기계학습');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (7, 'k겹 교차검증');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (10, 'React');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (10, '리액트 훅');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (10, '디버깅');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (11, '프로젝트');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (11, '디자인실무');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (11, '디자인협업');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (12, '컴포넌트');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (12, '아이콘');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (12, '오토레이아웃');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (13, '자바 스크립트');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (13, '변수');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (13, '콜백 함수');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (13, 'JavaScript');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (13, '화살표 함수');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (14, '기초 통계');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (14, '분산');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (14, '확률변수');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (14, '정규분포');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (14, '가설 검정');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (14, '신뢰수준');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (15, '기초 통계');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (15, 't-test');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (15, 't검정');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (16, '기초 통계');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (16, '분산분석');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (16, 'ANOVA');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (17, '컴포넌트');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (17, '아이콘');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (17, '오토레이아웃');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (18, '캐싱 기술');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (18, '데이터 무결성');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (18, '데이터 정합성');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (18, '데이터베이스 설계');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (19, '재무 보고서');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (19, '회계 자동화');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (19, '회계장부');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (20, '파이썬 게임');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (20, '미니프로젝트');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (20, 'Python');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (21, '창업');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (21, '스타트업');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (21, '서비스기획');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (22, '영어');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (22, '문법');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (23, '엑셀');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (23, '함수');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (23, '통계함수');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (24, '파이썬');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (24, '머신러닝');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (24, '크롤링');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (24, '업무자동화');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (8, '서비스기획');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (8, '린 캔버스');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (25, '파이썬');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (25, '욜로 모델');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (25, '머신러닝');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (25, '기계학습');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (26, '코틀린');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (26, '앱 개발');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (27, '토스');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (27, '오픽');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (28, '취준');
INSERT INTO learningflowdb.collection_keywords (collection_id, keyword) VALUES (28, '취업준비');
